### ISSUE TITLE
Wrong redirect URL

### ISSUE THREAD

**Issue by markovic-nikola** [austenc/vscode-laravel-docs#4]
Hi Austen,

I'm getting 404 since last update I guess, ending up at this URL: https://laravel.com/docs/7.x/7 for all commands (search queries).
Version: **1.5.0**

**Comment by austenc** [comment]
@markovic-nikola Thank you for reporting this! Sorry about that! Will get this fixed in the next day or so.

**Comment by mreduar** [comment]
Is the problem still present? Or is my extension out of date?

**Comment by austenc** [comment]
@markovic-nikola @MrEduar Would you mind testing out the new version to see if the problem is fixed for you? Note that you may need to reload vscode if you already had it open.

If you look at the extension version that's installed it should be `1.5.1` -- if this is fixed for you I'll close the issue, thanks again for reporting!

**Comment by mreduar** [comment]
Effectively the problem is solved, thank you very much. Its extension is very useful to read the documentation quickly. Thank you!

**Comment by austenc** [comment]
Great thank you @MrEduar !
